### PR TITLE
Add English translations

### PR DESCRIPTION
**Pull request by bkvogel**
Add English translations.
Thanks to Nobuyuki Ota for the initial translation from which my translation is based.

### CODE REVIEW

**Comment by mitmul** [comment]
Great, thank you very much! I'll check them again and soon merge it.

**Comment by bkvogel** [comment]
I've only added 1 so far, though. I'll remove the WIP label once I add all the notebooks.

**Comment by mitmul** [comment]
Ah, OK, sorry I misunderstood that you will separate PRs for each chapter. Thank you for working on this documentation work.

**Comment by bkvogel** [comment]
OK, I have added English documentation for all 4 notebooks and removed WIP, so they are ready to review.

**Pull request merged**
